version: '3.3'

services:
  apache:
    container_name: symfony-apache
    ports:
      - 6050:80
    build:
      context: .
      args:
        PHP_MODE: production
    restart: unless-stopped
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: symfony-mysql
    ports:
      - 6030:3306
    restart: unless-stopped
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: symfonydemo
      MYSQL_ROOT_PASSWORD: symfonypassword
    command: ['--default-authentication-plugin=mysql_native_password', '--character-set-server=utf8', '--collation-server=utf8_general_ci']

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: symfony-phpmyadmin
    ports:
      - "6070:80"
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: symfonypassword
    restart: always

volumes:
  db: